### ISSUE TITLE
idp.merge.properties still needed?

### ISSUE THREAD

**Issue by bugix** [iay/shibboleth-idp-docker#14]
New to the Shibboleth IdP world thankfully I found your tool and gave it a go on a clean host:

git clone
./fetch-jetty
./fetch-shib
Adjust SCOPE and HOST in install-idp
./install

I got:

`BUILD FAILED
/data/shibboleth-dist/bin/build.xml:20: net.shibboleth.utilities.java.support.logic.ConstraintViolationException: property 'idp.sealer.keyPassword' cannot be replaced
	at net.shibboleth.utilities.java.support.logic.Constraint.isFalse(Constraint.java:63)
	at net.shibboleth.idp.installer.PropertiesWithComments.replaceProperty(PropertiesWithComments.java:235)
	at net.shibboleth.idp.installer.PropertiesWithComments.replaceProperties(PropertiesWithComments.java:221)
	at net.shibboleth.idp.installer.V4Install.populatePropertyFiles(V4Install.java:249)
	at net.shibboleth.idp.installer.V4Install.execute(V4Install.java:106)
	at net.shibboleth.idp.installer.ant.impl.V4InstallTask.execute(V4InstallTask.java:95)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1391)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1254)
	at org.apache.tools.ant.Main.runBuild(Main.java:830)
	at org.apache.tools.ant.Main.startAnt(Main.java:223)
	at org.apache.tools.ant.Main.start(Main.java:190)
	at org.apache.tools.ant.Main.main(Main.java:274)`

After a bit of googling I found [https://issues.shibboleth.net/jira/browse/IDP-1556 ](https://issues.shibboleth.net/jira/browse/IDP-1556) which hints that IdP v4 no longer supports idp.sealer.storePassword and idp.sealer.keyPassword in idp.merge.properties. And indeed after starting from scratch and removing those entries the build succeeded.

Is idp.merge.properties still needed with v4?

**Comment by iay** [comment]
Sorry for the delay in looking at this, but I have finally found the time to review your PR. As a result I have squashed your three commits into one and aded it to my repository.

Many thanks!
